
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Sitecore.Feature.BoxWithModal.Templates
{
  #region Designer generated code

  using System;
  using Sitecore;
  using Sitecore.Diagnostics;
  using Sitecore.Data.Items;
  using Sitecore.Data.Fields;
  using Sitecore.Data;
  
      
  /// <summary>Represents the "_BoxWithModal" template.</summary>
  public partial class __BoxWithModal : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{0491116A-44CB-4ECD-B210-1DA10B69044C}");

    public __BoxWithModal(Item item) : base(item) {
    }

    public static class FieldIds {
      
      public static readonly ID BoxTitle = ID.Parse("{F35D2956-0D4C-42F8-B50A-2AA1E81D7ACC}");

      public static readonly ID BoxSubtitle = ID.Parse("{EC102602-45EF-478C-BEE9-44F47E6D5DB7}");

      public static readonly ID BoxImage = ID.Parse("{FC108CF0-6828-4D8B-8955-1F6936F19E3E}");

      public static readonly ID ModalTitle = ID.Parse("{0ABB10F3-7E15-4803-A7DE-21E184EC555C}");

      public static readonly ID ModalIntroText = ID.Parse("{EAA44868-4E8F-4D31-B109-61F0CF18C843}");

      public static readonly ID ModalImage = ID.Parse("{FDE400AF-E23B-4249-B46B-65F166CE50C0}");

      public static readonly ID ModalContent = ID.Parse("{73F1A95D-79B3-4B5C-AAB5-84EC7E804C59}");

    }
    
    /// <summary>Gets or sets the "Box title" field.</summary>
    public string BoxTitle 
    {
      get 
      {
        return this.InnerItem[FieldIds.BoxTitle];
      }
      set
      {
        this.InnerItem[FieldIds.BoxTitle] = value;
      }
    }
  
    /// <summary>Gets or sets the "Box subtitle" field.</summary>
    public string BoxSubtitle 
    {
      get 
      {
        return this.InnerItem[FieldIds.BoxSubtitle];
      }
      set
      {
        this.InnerItem[FieldIds.BoxSubtitle] = value;
      }
    }
  
    /// <summary>Gets the "Box image" field.</summary>
    public ImageField BoxImage 
    {
      get 
      {
        return this.InnerItem.Fields[FieldIds.BoxImage];
      }
    }
  
    /// <summary>Gets or sets the "Modal title" field.</summary>
    public string ModalTitle 
    {
      get 
      {
        return this.InnerItem[FieldIds.ModalTitle];
      }
      set
      {
        this.InnerItem[FieldIds.ModalTitle] = value;
      }
    }
  
    /// <summary>Gets or sets the "Modal intro text" field.</summary>
    public string ModalIntroText 
    {
      get 
      {
        return this.InnerItem[FieldIds.ModalIntroText];
      }
      set
      {
        this.InnerItem[FieldIds.ModalIntroText] = value;
      }
    }
  
    /// <summary>Gets the "Modal image" field.</summary>
    public ImageField ModalImage 
    {
      get 
      {
        return this.InnerItem.Fields[FieldIds.ModalImage];
      }
    }
  
    /// <summary>Gets or sets the "Modal content" field.</summary>
    public string ModalContent 
    {
      get 
      {
        return this.InnerItem[FieldIds.ModalContent];
      }
      set
      {
        this.InnerItem[FieldIds.ModalContent] = value;
      }
    }
  
    public static __BoxWithModal Create(Item item) 
    {
      return new __BoxWithModal(item);
    }

    public static implicit operator Item (__BoxWithModal item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator __BoxWithModal(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
  
  #endregion
}

#pragma warning restore 1591
