
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Sitecore.Feature.Identity.Templates
{
  #region Designer generated code

  using System;
  using Sitecore;
  using Sitecore.Diagnostics;
  using Sitecore.Data.Items;
  using Sitecore.Data.Fields;
  using Sitecore.Data;
  
      
  /// <summary>Represents the "_Identity" template.</summary>
  public partial class __Identity : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{BE2D9C65-CDEB-429D-A4F6-414F745A651B}");

    public __Identity(Item item) : base(item) {
    }

    public static class FieldIds {
      
      public static readonly ID SiteName = ID.Parse("{78569355-00D5-4063-B869-328BAEA58CD2}");

      public static readonly ID Copyright = ID.Parse("{70F1EC5F-5391-4C02-A330-5D7CED742E90}");

      public static readonly ID OrganizationName = ID.Parse("{3AD56A87-670A-438F-8FE5-707515C723FF}");

      public static readonly ID OrganizationEmail = ID.Parse("{2953BEE7-18D6-4230-92C3-457682A89F75}");

    }
    
    /// <summary>Gets or sets the "Site Name" field.</summary>
    public string SiteName 
    {
      get 
      {
        return this.InnerItem[FieldIds.SiteName];
      }
      set
      {
        this.InnerItem[FieldIds.SiteName] = value;
      }
    }
  
    /// <summary>Gets or sets the "Copyright" field.</summary>
    public string Copyright 
    {
      get 
      {
        return this.InnerItem[FieldIds.Copyright];
      }
      set
      {
        this.InnerItem[FieldIds.Copyright] = value;
      }
    }
  
    /// <summary>Gets or sets the "Organization Name" field.</summary>
    public string OrganizationName 
    {
      get 
      {
        return this.InnerItem[FieldIds.OrganizationName];
      }
      set
      {
        this.InnerItem[FieldIds.OrganizationName] = value;
      }
    }
  
    /// <summary>Gets or sets the "Organization Email" field.</summary>
    public string OrganizationEmail {
      get 
      {
        return this.InnerItem[FieldIds.OrganizationEmail];
      }
      set 
      {
        this.InnerItem[FieldIds.OrganizationEmail] = value;
      }
    }
  
    public static __Identity Create(Item item) 
    {
      return new __Identity(item);
    }

    public static implicit operator Item (__Identity item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator __Identity(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
  
  #endregion
}

#pragma warning restore 1591
