
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Sitecore.Basis.Dictionary.Templates
{
  #region Designer generated code

  using System;
  using Sitecore;
  using Sitecore.Diagnostics;
  using Sitecore.Data.Items;
  using Sitecore.Data.Fields;
  using Sitecore.Data;
  
      
  /// <summary>Represents the "Dictionary Folder" template.</summary>
  public partial class DictionaryFolder : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{A811B666-F7AD-4B24-8833-DACEE873106D}");

    public DictionaryFolder(Item item) : base(item) {
    }

    public static class FieldIds {
      
    }
    
    public static DictionaryFolder Create(Item item) 
    {
      return new DictionaryFolder(item);
    }

    public static implicit operator Item (DictionaryFolder item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator DictionaryFolder(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
      
  /// <summary>Represents the "Dictionary Entry" template.</summary>
  public partial class DictionaryEntry : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{09154788-3033-47D9-B5AB-5718B5F1372F}");

    public DictionaryEntry(Item item) : base(item) {
    }

    public static class FieldIds {
      
      public static readonly ID Phrase = ID.Parse("{41988B93-8E49-4A33-9337-2EFA35FC61D5}");

    }
    
    /// <summary>Gets or sets the "Phrase" field.</summary>
    public string Phrase 
    {
      get 
      {
        return this.InnerItem[FieldIds.Phrase];
      }
      set
      {
        this.InnerItem[FieldIds.Phrase] = value;
      }
    }
  
    public static DictionaryEntry Create(Item item) 
    {
      return new DictionaryEntry(item);
    }

    public static implicit operator Item (DictionaryEntry item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator DictionaryEntry(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
  
  #endregion
}

#pragma warning restore 1591
