
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Sitecore.Feature.TeamMember.Templates
{
  #region Designer generated code

  using System;
  using Sitecore;
  using Sitecore.Diagnostics;
  using Sitecore.Data.Items;
  using Sitecore.Data.Fields;
  using Sitecore.Data;
  
      
  /// <summary>Represents the "_TeamMember" template.</summary>
  public partial class __TeamMember : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{3FD97373-94E2-4C38-A7DB-7FF3141492DD}");

    public __TeamMember(Item item) : base(item) {
    }

    public static class FieldIds {
      
      public static readonly ID Name = ID.Parse("{95BD8AF6-EE12-4602-A056-9BC9497857C9}");

      public static readonly ID Role = ID.Parse("{B2CF3BF3-0DE7-495B-99FF-1319343C8063}");

      public static readonly ID Picture = ID.Parse("{47C1237C-36F5-4BC9-B98B-4FE424F307C2}");

      public static readonly ID Twitter = ID.Parse("{631AF1FC-3E3A-445B-8766-A00657C55300}");

      public static readonly ID Facebook = ID.Parse("{2F1EC3AE-FDA9-483B-8AE8-8B71FEDB1CB9}");

      public static readonly ID LinkedIn = ID.Parse("{A9100FC4-CE6F-4D7C-B66B-BEA47115F662}");

    }
    
    /// <summary>Gets or sets the "Name" field.</summary>
    public string Name 
    {
      get 
      {
        return this.InnerItem[FieldIds.Name];
      }
      set
      {
        this.InnerItem[FieldIds.Name] = value;
      }
    }
  
    /// <summary>Gets or sets the "Role" field.</summary>
    public string Role 
    {
      get 
      {
        return this.InnerItem[FieldIds.Role];
      }
      set
      {
        this.InnerItem[FieldIds.Role] = value;
      }
    }
  
    /// <summary>Gets the "Picture" field.</summary>
    public ImageField Picture 
    {
      get 
      {
        return this.InnerItem.Fields[FieldIds.Picture];
      }
    }
  
    /// <summary>Gets or sets the "Twitter" field.</summary>
    public string Twitter {
      get 
      {
        return this.InnerItem[FieldIds.Twitter];
      }
      set 
      {
        this.InnerItem[FieldIds.Twitter] = value;
      }
    }
  
    /// <summary>Gets or sets the "Facebook" field.</summary>
    public string Facebook {
      get 
      {
        return this.InnerItem[FieldIds.Facebook];
      }
      set 
      {
        this.InnerItem[FieldIds.Facebook] = value;
      }
    }
  
    /// <summary>Gets or sets the "LinkedIn" field.</summary>
    public string LinkedIn {
      get 
      {
        return this.InnerItem[FieldIds.LinkedIn];
      }
      set 
      {
        this.InnerItem[FieldIds.LinkedIn] = value;
      }
    }
  
    public static __TeamMember Create(Item item) 
    {
      return new __TeamMember(item);
    }

    public static implicit operator Item (__TeamMember item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator __TeamMember(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
  
  #endregion
}

#pragma warning restore 1591
