
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Sitecore.Feature.Service.Templates
{
  #region Designer generated code

  using System;
  using Sitecore;
  using Sitecore.Diagnostics;
  using Sitecore.Data.Items;
  using Sitecore.Data.Fields;
  using Sitecore.Data;
  
      
  /// <summary>Represents the "_Service" template.</summary>
  public partial class __Service : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{AFC3B61C-5F89-40C7-B9C5-2213C6DE1EE6}");

    public __Service(Item item) : base(item) {
    }

    public static class FieldIds {
      
      public static readonly ID Heading = ID.Parse("{F992F229-88DA-42E7-B5DC-5DC6F1413C93}");

      public static readonly ID Text = ID.Parse("{E40855CB-B25E-42BB-A804-3491583C5130}");

      public static readonly ID IconCSSClass = ID.Parse("{A73C362A-D9E7-4027-BA03-E3167A5CA888}");

    }
    
    /// <summary>Gets or sets the "Heading" field.</summary>
    public string Heading 
    {
      get 
      {
        return this.InnerItem[FieldIds.Heading];
      }
      set
      {
        this.InnerItem[FieldIds.Heading] = value;
      }
    }
  
    /// <summary>Gets or sets the "Text" field.</summary>
    public string Text 
    {
      get 
      {
        return this.InnerItem[FieldIds.Text];
      }
      set
      {
        this.InnerItem[FieldIds.Text] = value;
      }
    }
  
    /// <summary>Gets or sets the "Icon CSS Class" field.</summary>
    public string IconCSSClass 
    {
      get 
      {
        return this.InnerItem[FieldIds.IconCSSClass];
      }
      set
      {
        this.InnerItem[FieldIds.IconCSSClass] = value;
      }
    }
  
    public static __Service Create(Item item) 
    {
      return new __Service(item);
    }

    public static implicit operator Item (__Service item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator __Service(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
  
  #endregion
}

#pragma warning restore 1591
