
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Sitecore.Feature.Multisite.Templates
{
  #region Designer generated code

  using System;
  using Sitecore;
  using Sitecore.Diagnostics;
  using Sitecore.Data.Items;
  using Sitecore.Data.Fields;
  using Sitecore.Data;
  
      
  /// <summary>Represents the "_SiteConfiguration" template.</summary>
  public partial class __SiteConfiguration : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{DFBEB1D4-441B-44A8-8E7E-3284375A55DE}");

    public __SiteConfiguration(Item item) : base(item) {
    }

    public static class FieldIds {
      
      public static readonly ID ShowInMenu = ID.Parse("{9B944550-069D-4544-8C42-111C302BF69D}");

      public static readonly ID Title = ID.Parse("{FEBE343D-0437-46B2-A4B9-8D911CFD0F5A}");

    }
    
    /// <summary>Gets or sets the "Show in Menu" field.</summary>
    public bool ShowInMenu 
    {
      get 
      {
        return MainUtil.GetBool(this.InnerItem[FieldIds.ShowInMenu], false);
      }
      set 
      {
        this.InnerItem[FieldIds.ShowInMenu] = value ? "1" : string.Empty;
      }
    }
  
    /// <summary>Gets or sets the "Title" field.</summary>
    public string Title 
    {
      get 
      {
        return this.InnerItem[FieldIds.Title];
      }
      set
      {
        this.InnerItem[FieldIds.Title] = value;
      }
    }
  
    public static __SiteConfiguration Create(Item item) 
    {
      return new __SiteConfiguration(item);
    }

    public static implicit operator Item (__SiteConfiguration item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator __SiteConfiguration(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
  
  #endregion
}

#pragma warning restore 1591
