
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Sitecore.Feature.Timeline.Templates
{
  #region Designer generated code

  using System;
  using Sitecore;
  using Sitecore.Diagnostics;
  using Sitecore.Data.Items;
  using Sitecore.Data.Fields;
  using Sitecore.Data;
  
      
  /// <summary>Represents the "_Timeline entry" template.</summary>
  public partial class __TimelineEntry : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{F4C95619-5B24-4CF3-A66D-30235781A2B8}");

    public __TimelineEntry(Item item) : base(item) {
    }

    public static class FieldIds {
      
      public static readonly ID Heading = ID.Parse("{20AB9787-F55C-40AF-8190-33D12557244C}");

      public static readonly ID Subheading = ID.Parse("{B69883C0-9DDE-4B49-909F-37758B563E7C}");

      public static readonly ID Body = ID.Parse("{3F71B7A7-3C50-498F-9020-48C8DFF341DF}");

      public static readonly ID Image = ID.Parse("{3CD351FA-4931-4809-8A34-F18D43E0741E}");

      public static readonly ID CSSClass = ID.Parse("{37236BB5-0F39-4D21-9CE6-9FA8BBB06A64}");

    }
    
    /// <summary>Gets or sets the "Heading" field.</summary>
    public string Heading 
    {
      get 
      {
        return this.InnerItem[FieldIds.Heading];
      }
      set
      {
        this.InnerItem[FieldIds.Heading] = value;
      }
    }
  
    /// <summary>Gets or sets the "Subheading" field.</summary>
    public string Subheading 
    {
      get 
      {
        return this.InnerItem[FieldIds.Subheading];
      }
      set
      {
        this.InnerItem[FieldIds.Subheading] = value;
      }
    }
  
    /// <summary>Gets or sets the "Body" field.</summary>
    public string Body 
    {
      get 
      {
        return this.InnerItem[FieldIds.Body];
      }
      set
      {
        this.InnerItem[FieldIds.Body] = value;
      }
    }
  
    /// <summary>Gets the "Image" field.</summary>
    public ImageField Image 
    {
      get 
      {
        return this.InnerItem.Fields[FieldIds.Image];
      }
    }
  
    /// <summary>Gets or sets the "CSS Class" field.</summary>
    public string CSSClass 
    {
      get 
      {
        return this.InnerItem[FieldIds.CSSClass];
      }
      set
      {
        this.InnerItem[FieldIds.CSSClass] = value;
      }
    }
  
    public static __TimelineEntry Create(Item item) 
    {
      return new __TimelineEntry(item);
    }

    public static implicit operator Item (__TimelineEntry item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator __TimelineEntry(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
      
  /// <summary>Represents the "_Timeline" template.</summary>
  public partial class __Timeline : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{3A636F9A-C491-4B8F-8073-D2ADFBAF2404}");

    public __Timeline(Item item) : base(item) {
    }

    public static class FieldIds {
      
    }
    
    public static __Timeline Create(Item item) 
    {
      return new __Timeline(item);
    }

    public static implicit operator Item (__Timeline item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator __Timeline(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
  
  #endregion
}

#pragma warning restore 1591
